language: python

install:
 - pip install -r requirements.txt

script:
 - pytest


services:
  - docker

before_install:
  - docker pull selenium/node-firefox
  - docker pull selenium/hub
  - docker run -d -p 4444:4444 --name selenium-hub selenium/hub
  - docker run -d --link selenium-hub:hub --name selenium-node-firefox -v /dev/shm:/dev/shm selenium/node-firefox