language: python

install:
 - pip install -r requirements.txt

script:
 - pytest


services:
  - docker

before_install:
  - docker pull selenium/node-chrome:3.141.59-vanadium
  - docker pull selenium/hub:3.141.59-vanadium
  - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.141.59-vanadium
  - docker run -d --link selenium-hub:hub --name selenium-node-chrome -v /dev/shm:/dev/shm selenium/node-chrome:3.141.59-vanadium